#include "zconfiginfo.h"
#include <QSettings>
#include <QDir>
ZConfigInfo* ZConfigInfo::m_pInstance=NULL;
qint32 ZConfigInfo::ZWriteConfigFile()
{
    QSettings tConfFile(QDir::currentPath()+"/OA.ini",QSettings::IniFormat);
    ////////////////////////////////////////
    tConfFile.beginGroup("OAInfo");
    tConfFile.setValue("IP",this->OAIPAddr);
    tConfFile.setValue("User",this->OAUserName);
    tConfFile.setValue("Pass",this->OAPassword);
    tConfFile.setValue("PostOnTimes",this->OAPostOnTimes);
    tConfFile.setValue("PostOffTimes",this->OAPostOffTimes);
    tConfFile.endGroup();
    ////////////////////////////////////////
    tConfFile.beginGroup("Time");
    tConfFile.setValue("MonEn",this->DayEnabled[0]);
    tConfFile.setValue("MonOnTime",this->OnTime[0]);
    tConfFile.setValue("MonAutoExitOn",this->AutoExitAfterOn[0]);
    tConfFile.setValue("MonOffTime",this->OffTime[0]);
    tConfFile.setValue("MonAutoExitOff",this->AutoExitAfterOff[0]);
    //////////////////////////////////////////////////
    tConfFile.setValue("TueEn",this->DayEnabled[1]);
    tConfFile.setValue("TueOnTime",this->OnTime[1]);
    tConfFile.setValue("TueAutoExitOn",this->AutoExitAfterOn[1]);
    tConfFile.setValue("TueOffTime",this->OffTime[1]);
    tConfFile.setValue("TueAutoExitOff",this->AutoExitAfterOff[1]);
    /////////////////////////////////////////////////
    tConfFile.setValue("WedEn",this->DayEnabled[2]);
    tConfFile.setValue("WedOnTime",this->OnTime[2]);
    tConfFile.setValue("WedAutoExitOn",this->AutoExitAfterOn[2]);
    tConfFile.setValue("WedOffTime",this->OffTime[2]);
    tConfFile.setValue("WedAutoExitOff",this->AutoExitAfterOff[2]);
    //////////////////////////////////////////////////
    tConfFile.setValue("ThuEn",this->DayEnabled[3]);
    tConfFile.setValue("ThuOnTime",this->OnTime[3]);
    tConfFile.setValue("ThuAutoExitOn",this->AutoExitAfterOn[3]);
    tConfFile.setValue("ThuOffTime",this->OffTime[3]);
    tConfFile.setValue("ThuAutoExitOff",this->AutoExitAfterOff[3]);
    ////////////////////////////////////////////////////
    tConfFile.setValue("FriEn",this->DayEnabled[4]);
    tConfFile.setValue("FriOnTime",this->OnTime[4]);
    tConfFile.setValue("FriAutoExitOn",this->AutoExitAfterOn[4]);
    tConfFile.setValue("FriOffTime",this->OffTime[4]);
    tConfFile.setValue("FriAutoExitOff",this->AutoExitAfterOff[4]);
    //////////////////////////////////////////////////
    tConfFile.setValue("SatEn",this->DayEnabled[5]);
    tConfFile.setValue("SatOnTime",this->OnTime[5]);
    tConfFile.setValue("SatAutoExitOn",this->AutoExitAfterOn[5]);
    tConfFile.setValue("SatOffTime",this->OffTime[5]);
    tConfFile.setValue("SatAutoExitOff",this->AutoExitAfterOff[5]);
    ////////////////////////////////////////////////////////
    tConfFile.setValue("SunEn",this->DayEnabled[6]);
    tConfFile.setValue("SunOnTime",this->OnTime[6]);
    tConfFile.setValue("SunAutoExitOn",this->AutoExitAfterOn[6]);
    tConfFile.setValue("SunOffTime",this->OffTime[6]);
    tConfFile.setValue("SunAutoExitOff",this->AutoExitAfterOff[6]);
    tConfFile.endGroup();
    ////////////////////////////////////////
    tConfFile.beginGroup("Email");
    tConfFile.setValue("SMTP",this->EmailSMTPAddr);
    //tConfFile.setValue("Sender",this->EmailSender);
    //tConfFile.setValue("SenderPassword",this->EmailSenderPassword);
    tConfFile.setValue("SendAlive",this->AliveEmailEnabled);
    tConfFile.setValue("SendResult",this->PostResultEnabled);
    tConfFile.endGroup();
    ////////////////////////////////
    return 0;
}
qint32 ZConfigInfo::ZReadConfigFile()
{
    QSettings tConfFile(QDir::currentPath()+"/OA.ini",QSettings::NativeFormat);
    ////////////////////////////////////////
    tConfFile.beginGroup("OAInfo");
    this->OAIPAddr=tConfFile.value("IP","119.10.114.11").toString();
    this->OAUserName=tConfFile.value("User","root").toString();
    this->OAPassword=tConfFile.value("Pass","root").toString();
    this->OAPostOnTimes=tConfFile.value("PostOnTimes",1).toInt();
    this->OAPostOffTimes=tConfFile.value("PostOffTimes",1).toInt();
    tConfFile.endGroup();
    ////////////////////////////////////////
    tConfFile.beginGroup("Time");
    this->DayEnabled[0]=tConfFile.value("MonEn",1).toInt();
    this->OnTime[0]=tConfFile.value("MonOnTime","09:00:00").toString();
    this->AutoExitAfterOn[0]=tConfFile.value("MonAutoExitOn",0).toInt();
    this->OffTime[0]=tConfFile.value("MonOffTime","18:00:00").toString();
    this->AutoExitAfterOff[0]=tConfFile.value("MonAutoExitOff",0).toInt();
    //////////////////////////////////////////////////
    this->DayEnabled[1]=tConfFile.value("TueEn",1).toInt();
    this->OnTime[1]=tConfFile.value("TueOnTime","09:00:00").toString();
    this->AutoExitAfterOn[1]=tConfFile.value("TueAutoExitOn",0).toInt();
    this->OffTime[1]=tConfFile.value("TueOffTime","18:00:00").toString();
    this->AutoExitAfterOff[1]=tConfFile.value("TueAutoExitOff",0).toInt();
    /////////////////////////////////////////////////
    this->DayEnabled[2]=tConfFile.value("WedEn",1).toInt();
    this->OnTime[2]=tConfFile.value("WedOnTime","09:00:00").toString();
    this->AutoExitAfterOn[2]=tConfFile.value("WedAutoExitOn",0).toInt();
    this->OffTime[2]=tConfFile.value("WedOffTime","18:00:00").toString();
    this->AutoExitAfterOff[2]=tConfFile.value("WedAutoExitOff",0).toInt();
    //////////////////////////////////////////////////
    this->DayEnabled[3]=tConfFile.value("ThuEn",1).toInt();
    this->OnTime[3]=tConfFile.value("ThuOnTime","09:00:00").toString();
    this->AutoExitAfterOn[3]=tConfFile.value("ThuAutoExitOn",0).toInt();
    this->OffTime[3]=tConfFile.value("ThuOffTime","18:00:00").toString();
    this->AutoExitAfterOff[3]=tConfFile.value("ThuAutoExitOff",0).toInt();
    ////////////////////////////////////////////////////
    this->DayEnabled[4]=tConfFile.value("FriEn",1).toInt();
    this->OnTime[4]=tConfFile.value("FriOnTime","09:00:00").toString();
    this->AutoExitAfterOn[4]=tConfFile.value("FriAutoExitOn",0).toInt();
    this->OffTime[4]=tConfFile.value("FriOffTime","18:00:00").toString();
    this->AutoExitAfterOff[4]=tConfFile.value("FriAutoExitOff",0).toInt();
    //////////////////////////////////////////////////
    this->DayEnabled[5]=tConfFile.value("SatEn",1).toInt();
    this->OnTime[5]=tConfFile.value("SatOnTime","09:00:00").toString();
    this->AutoExitAfterOn[5]=tConfFile.value("SatAutoExitOn",0).toInt();
    this->OffTime[5]=tConfFile.value("SatOffTime","18:00:00").toString();
    this->AutoExitAfterOff[5]=tConfFile.value("SatAutoExitOff",0).toInt();
    ////////////////////////////////////////////////////////
    this->DayEnabled[6]=tConfFile.value("SunEn",1).toInt();
    this->OnTime[6]=tConfFile.value("SunOnTime","09:00:00").toString();
    this->AutoExitAfterOn[6]=tConfFile.value("SunAutoExitOn",0).toInt();
    this->OffTime[6]=tConfFile.value("SunOffTime","18:00:00").toString();
    this->AutoExitAfterOff[6]=tConfFile.value("SunAutoExitOff",0).toInt();
    tConfFile.endGroup();
    ////////////////////////////////////////
    tConfFile.beginGroup("Email");
    this->EmailSMTPAddr=tConfFile.value("SMTP","smtp.163.com").toString();
    this->EmailSender=tConfFile.value("Sender","root@yantai.com").toString();
    this->EmailSenderPassword=tConfFile.value("SenderPassword","root").toString();
    this->AliveEmailEnabled=tConfFile.value("SendAlive",0).toInt();
    this->PostResultEnabled=tConfFile.value("SendResult",0).toInt();
    tConfFile.endGroup();
    ////////////////////////////////
    return 0;
}
